#! /bin/sh

### BEGIN INIT INFO
# Provides:          nspamper
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nspamper dyndns client
# Description:       starts/stops the nsupdates dyndns client daemon nspamper
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=nspamper
DAEMON=/usr/sbin/$NAME
DESC="NS Pamper daemon"
conf=/etc/nspamper.conf

test -f $DAEMON || exit 0
test -r $conf || exit 0
grep '^exit\>' /etc/nspamper.conf >/dev/null && exit 0;

set -e


piddir=/var/run
pidfile=$piddir/$NAME.pid


case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $piddir
	start-stop-daemon --start --quiet --pidfile $pidfile \
		--exec $DAEMON --
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $pidfile
	echo "$NAME."
	;;
  restart|force-reload)
	echo "Restarting $DESC: ..."
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
